package BurgerBarn;

import javax.swing.JOptionPane;


/**
 *
 * @author Johnny Romano
 */
public class BurgerBarnGUI extends javax.swing.JFrame {

    private Order order;
    
    
    /**
     * Creates new form BurgerBarnGUI
     */
    public BurgerBarnGUI() {
        order = new Order();
        // call GUI components
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupBurgers = new javax.swing.ButtonGroup();
        jRadioSingle = new javax.swing.JRadioButton();
        jRadioDouble = new javax.swing.JRadioButton();
        jCheckBoxAddCheese = new javax.swing.JCheckBox();
        jCheckBoxAddBacon = new javax.swing.JCheckBox();
        jCheckBoxMeal = new javax.swing.JCheckBox();
        jlblPrice = new javax.swing.JLabel();
        jtxtPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jlblQuantity = new javax.swing.JLabel();
        jtxtQuantity = new javax.swing.JTextField();
        jlblTotal = new javax.swing.JLabel();
        jtxtOrder = new javax.swing.JTextField();
        jlblYourOrder = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuAdd = new javax.swing.JMenuItem();
        jMenuClear = new javax.swing.JMenuItem();
        jMenuNew = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 340));

        buttonGroupBurgers.add(jRadioSingle);
        jRadioSingle.setMnemonic('s');
        jRadioSingle.setText("Single Burger");
        jRadioSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSingleActionPerformed(evt);
            }
        });

        buttonGroupBurgers.add(jRadioDouble);
        jRadioDouble.setMnemonic('d');
        jRadioDouble.setText("Double Burger");
        jRadioDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDoubleActionPerformed(evt);
            }
        });

        jCheckBoxAddCheese.setMnemonic('c');
        jCheckBoxAddCheese.setText("Add cheese");
        jCheckBoxAddCheese.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jCheckBoxAddCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAddCheeseActionPerformed(evt);
            }
        });

        jCheckBoxAddBacon.setMnemonic('b');
        jCheckBoxAddBacon.setText("Add bacon");
        jCheckBoxAddBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAddBaconActionPerformed(evt);
            }
        });

        jCheckBoxMeal.setMnemonic('m');
        jCheckBoxMeal.setText("Make it a meal");
        jCheckBoxMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMealActionPerformed(evt);
            }
        });

        jlblPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblPrice.setText("Item Price");

        jtxtPrice.setEditable(false);
        jtxtPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtPrice.setText(" $ 0.00");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextArea1.setRows(25);
        jScrollPane1.setViewportView(jTextArea1);

        jlblQuantity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblQuantity.setText("Quantity");

        jtxtQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtQuantity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtQuantity.setText("1");
        jtxtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtQuantityActionPerformed(evt);
            }
        });

        jlblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblTotal.setText("Order Total");

        jtxtOrder.setEditable(false);
        jtxtOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtOrder.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtOrder.setText("$ 0.00");

        jlblYourOrder.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblYourOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblYourOrder.setText("Your Order");
        jlblYourOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jMenuFile.setText("File");

        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuExit);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Edit");

        jMenuAdd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_RIGHT, java.awt.event.InputEvent.ALT_MASK));
        jMenuAdd.setText("Add to Order");
        jMenuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAddActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuAdd);

        jMenuClear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.ALT_MASK));
        jMenuClear.setText("Clear for next item");
        jMenuClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClearActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuClear);

        jMenuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DOWN, java.awt.event.InputEvent.ALT_MASK));
        jMenuNew.setText("New Order");
        jMenuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuNew);

        jMenuBar1.add(jMenuEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioSingle)
                            .addComponent(jRadioDouble))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBoxAddCheese, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBoxAddBacon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBoxMeal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtOrder)
                            .addComponent(jtxtQuantity)
                            .addComponent(jtxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlblYourOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtOrder, jtxtPrice, jtxtQuantity});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblYourOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBoxAddBacon))
                                .addGap(17, 17, 17)
                                .addComponent(jCheckBoxAddCheese, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtPrice))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jRadioDouble, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCheckBoxAddBacon, jCheckBoxAddCheese, jCheckBoxMeal, jRadioDouble, jRadioSingle, jlblPrice, jlblQuantity, jlblTotal, jtxtOrder, jtxtPrice, jtxtQuantity});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAddActionPerformed
        // TODO add your handling code here:
        try 
        {
        if(!jRadioSingle.isSelected() &&
                !jRadioDouble.isSelected())
            {
                JOptionPane.showMessageDialog(null, "Select Single or Double Burger");
                jRadioSingle.requestFocusInWindow();
                return;
            }
            
        if(jtxtQuantity.getText() != "0")
            {
                order.setOrderQty(Integer.parseInt(jtxtQuantity.getText()));
            }
        
        if(jtxtQuantity.getText().isEmpty() ||
                Integer.parseInt(jtxtQuantity.getText()) < 1)
            {
                JOptionPane.showMessageDialog(null, "Enter Quantity > 0");
                jtxtQuantity.requestFocusInWindow();
                return;
            }
        }
        catch (NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Enter number not letter!");
            return;
        }
        
        if (jRadioSingle.isSelected())
        {
         order.setOrder("Single Burger");
        }
        
        if (jRadioDouble.isSelected())
        {
            order.setOrder("Double Burger");
        }
        
        if (jCheckBoxAddBacon.isSelected())
        {
            order.setOrder("add Bacon");
        }
        
        if (jCheckBoxAddCheese.isSelected())
        {
            order.setOrder("w/ Cheese");
        }
        
        if (jCheckBoxMeal.isSelected())
        {
            order.setOrder("make it a Meal");
        }
        
        jTextArea1.append("Qty:" + order.getOrderQty() + " | " + order.getOrder() + " at " + order.getTotal() + "\n");
        jtxtOrder.setText("$" + order.getTotalOrder());
        
        // jTextArea1.append(order.getTotal());
        clearOptions();
        
    }//GEN-LAST:event_jMenuAddActionPerformed

    private void calcItemPrice()
    {
        
    }
    
    private void jCheckBoxMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMealActionPerformed
        // TODO add your handling code here:
        
        if (jCheckBoxMeal.isSelected())
        {
            order.setMeal(4.00);
         
        }
        else
        {
            order.setMeal(-4.00);
         
        }
        
        jtxtPrice.setText("$ " + order.getTotal());
    }//GEN-LAST:event_jCheckBoxMealActionPerformed

    private void jCheckBoxAddBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAddBaconActionPerformed
        if (jCheckBoxAddBacon.isSelected())
        {
            order.setExtraBacon(1.25);
            
        }   
        if (!jCheckBoxAddBacon.isSelected())
        {
            order.setExtraBacon(-1.25);
            
        }           
        jtxtPrice.setText("$ " + order.getTotal());
    }//GEN-LAST:event_jCheckBoxAddBaconActionPerformed

    private void calcCurrentPrice()
    {
        if (jCheckBoxAddCheese.isSelected())
        {
            order.setExtraCheese(0.50);
        }  
        else 
        {
            order.setExtraCheese(-0.50);
        }
        
        jtxtPrice.setText("$ " + order.getTotal());
    }
    
    
    private void clearOptions()
    {
        jtxtQuantity.setText("1");
        jtxtPrice.setText("$ 0.00");
        buttonGroupBurgers.clearSelection();
        jCheckBoxAddBacon.setSelected(false);
        jCheckBoxAddCheese.setSelected(false);
        jCheckBoxMeal.setSelected(false);
        order.clearOrder();
    }
    public void clearOrder()
    {
        clearOptions();
        jTextArea1.setText("");
        jtxtOrder.setText("$ 0.00");
        order.clearOrder();
    }
    
    private void jMenuClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClearActionPerformed
        // TODO add your handling code here:
        clearOptions();  
    }//GEN-LAST:event_jMenuClearActionPerformed

    private void jMenuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNewActionPerformed
        // TODO add your handling code here:
        clearOrder();
        order.clearAll();
        
        
    }//GEN-LAST:event_jMenuNewActionPerformed

    private void jRadioSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSingleActionPerformed
        // TODO add your handling code here:
        
        order.setQty(1);
        jtxtPrice.setText("$ " + order.getTotal());
        
    }//GEN-LAST:event_jRadioSingleActionPerformed

    private void jRadioDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDoubleActionPerformed
        // TODO add your handling code here:
        
        order.setQty(2);
        jtxtPrice.setText("$ " + order.getTotal());
    }//GEN-LAST:event_jRadioDoubleActionPerformed

    private void jtxtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtQuantityActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtxtQuantityActionPerformed

    private void jCheckBoxAddCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAddCheeseActionPerformed
        // TODO add your handling code here:
        calcCurrentPrice();
    }//GEN-LAST:event_jCheckBoxAddCheeseActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BurgerBarnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BurgerBarnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BurgerBarnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BurgerBarnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BurgerBarnGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupBurgers;
    private javax.swing.JCheckBox jCheckBoxAddBacon;
    private javax.swing.JCheckBox jCheckBoxAddCheese;
    private javax.swing.JCheckBox jCheckBoxMeal;
    private javax.swing.JMenuItem jMenuAdd;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuClear;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuNew;
    private javax.swing.JRadioButton jRadioDouble;
    private javax.swing.JRadioButton jRadioSingle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlblPrice;
    private javax.swing.JLabel jlblQuantity;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JLabel jlblYourOrder;
    private javax.swing.JTextField jtxtOrder;
    private javax.swing.JTextField jtxtPrice;
    private javax.swing.JTextField jtxtQuantity;
    // End of variables declaration//GEN-END:variables
}
